language: elixir
sudo: false
elixir:
  - 1.4
otp_release:
  - 18.3
  - 19.1
env:
  - MIX_ENV=test
script:
  - mix eqc.install --mini
  - mix coveralls.travis
notifications:
  recipients:
    - paulschoenfelder@gmail.com
